version: '3.9'

services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: ufood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - ufood_backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    networks:
      - ufood_backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  ufood_backend:
    driver: bridge